### ISSUE TITLE
Bad CORE_PEER_MSPCONFIGPATH setting in Hyperledger stack

### ISSUE THREAD

**Issue by hierozbosch** [awsdocs/aws-blockchain-templates-developer-guide#1]
AWS Hyperledger template sets environment variable CORE_PEER_MSPCONFIGPATH incorrectly, adding an extra space char in the path:

CORE_PEER_MSPCONFIGPATH=/opt /gopath/src/github.com/hyperledger/fabric/peer/crypto/...

Note space char separating /opt /gopath.

**Comment by Pahtoe** [comment]
Thanks for reporting this. I forwarded on to the ENG team and just got word that the fix is implemented.
