### ISSUE TITLE
chaisfitzwater@gmail.com

### ISSUE THREAD

**Issue by ETCorps** [awsdocs/aws-blockchain-templates-developer-guide#13]
https://etherscan.io/address/0x000000000000000000000000000000000000000017:00

N

*

⚫ etherscan.io

ETH P $3,912.07 (2.15%) Gas 21 al

Search by Address/Tan Hash / Block / Token/Domal

Etherscan

Home

Blockchain v

Tokens

NFTS

Resources

Developers

More

Sign In

Contract 0x464C71f6c2F760DA50930CB91CZ4:3965460186 #

Exchange

Sponsored

CryptoSlots-$1,000,000 Jackpot & Frovably Far Casino

Games Click for games!

Aave have Collector V2

Source Code

More

Overview

More Info

Multi Chain

ETH BALANCE 104.543066032265952275 ETH

PRIVATE NAME TAGS

MALTICHAIN ADDRESSES Saddresses found in Blockc

+Add

ETH VALUE

$199,914:57 ($7,9722/ETH

CONTRACT CREATOR Aave Depilat xx331087592581500

BC.GAME Welcome bonus

up to 500 ETH PLAY NOW

FOREN HOLDINGS $16,791,146.84 (T)

Transactions

Internal Transactions

Token Transters (ERC-20)

Contract

Analytics

Comments

LE Latest 5 from a total of 5 transactions

(Pending)

Transaction Hash

Method

Age

From V

To

xd407a6646388949

(pending)

7 days ago

Ox7603247055914

Aave A Colle

0x183f0159a4c302d6

16605916

53 days 8 hrs ago

Ox31513F82d0e184

Aave Aave Co

16173504

113 days 17 hrs ago

0x788847, 50390063

Aave Aave Co

0x211697658359

15173495

112 days 17 hrs ago

0x788847.50190063

Aave Aave Co

0x6147c76272cdb7ef1.

11274999

869 days 11 hrs ago

Aaver Deployer 6

Aave Aave Co

Ux33108759258a1800

11274810 669 days 11 hes ago Aave: Deployer 60

Create: Initia

[Download CV Export

A contract address hosts a smart contact, which is a sat at code stared on the blockchain that runs when praatarminant constions are met.

I am more about addresses in

+ Back to Top

Company

Community

Products & Services

Powered by Ethereum

API Documentation

Advertise

Etherscan is a Block Explorer and Analytics Platform for

Brand Assets

Ethereum, a decentralized smart contracts platform

Knowledge Base

Explorer as a Service (as)

Contact Us

Network Status

APP

Cancers We H

Newsletters

Printy Support

Terms of Service

Disqus Comments

Bug Bounty

Blockscan Chat

heracan 2023 (1)

Donations By71765

9761

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
