### ISSUE TITLE
>` Add. Project@ETCorps, file.create.project`

### ISSUE THREAD

**Issue by ETCorps** [awsdocs/aws-blockchain-templates-developer-guide#26]
>` Add. Project@ETCorps, file.create.project`

_Originally posted by @ETCorps in https://github.com/ETCorps/turbo-halibut/issues/23#issuecomment-1535261964_

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
