### ISSUE TITLE
Share via wallet for payment method 

### ISSUE THREAD

**Issue by ETCorps** [awsdocs/aws-blockchain-templates-developer-guide#7]
https://bitinfocharts.com/bitcoin/block/768493/3MvYswDnJKTuHQQaTevYFiVw7b5RSnLG1U

768493 2022-12-22 07:52:21	+6.34 BTC 	6.34 BTC	$106,184 @ $16,748.21

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
